repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: yapf -ir -vv ./src
        language: system
        always_run: true
        pass_filenames: false